name: Swift
on: [push]
jobs:
  units:
    name: Unit Tests
    strategy:
      matrix:
        os: [macos-latest, macos-12, macos-11, macos-10.15]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: swift test

  vectors-not-stale:
    name: Check Test Vectors Up To Date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for updates
        run: |
          cd Tests/PasetoTests/TestVectors
          rm *
          wget https://raw.githubusercontent.com/paseto-standard/test-vectors/master/v{1..4}.json
          git diff --exit-code
